### PR TITLE
Recursive dependency detection

### LINKED ISSUE #10: Detect Recursive References
## The Problem
It can happen that during resolution of a service, its own definition gets invoked. In these cases, it can become quite hard to debug by looking at just a stack trace.

## Suggested Solution
Implement recursion detection, such that an exception is thrown if a service definition invokes itself, directly or not.

### PR DESCRIPTION
**Pull request by mecha**
Solution for #10

### CODE REVIEW

File: src/DelegatingContainer.php [hunk 1]
```diff
@@ -38,43 +38,88 @@ public function __construct(ServiceProviderInterface $provider, PsrContainerInte
      * {@inheritDoc}
      */
     public function get($id)
+    {
+        static $stack = [];
```
Comment (XedinUnknown) [inline src/DelegatingContainer.php]: What is the advantage of using a `static` variable VS property?

**Review by XedinUnknown — CHANGES_REQUESTED** [review]
Great addition! Just one question.

File: src/DelegatingContainer.php (hunk 1 above)
Comment (mecha) [reply src/DelegatingContainer.php]: Functionally equivalent.

A static variable makes more sense for me here, since it's an implementation detail of the _function_. A class property would imply that it's some form of state or cache related to the parent class, and I don't consider this temporary stack to be either of those things.

Comment (XedinUnknown) [reply src/DelegatingContainer.php]: Seems like this implementation relies on every actual access to a service being done via an instance of the same class: every time _its_ `get()` method runs, the stack will have a service name pushed onto it. So from my perspective, it is a stack of retrievals from the `DelegatingContainer`, and therefore pertains to the class instance.

Comment (XedinUnknown) [reply src/DelegatingContainer.php]: The bigger problem is that `static` inside a class method will point to the same value _for any instance of that class_. So if somewhere in a service definition a `get()` method of an entirely different `DelegatingContainer` is used, this will push onto the stack.

Comment (XedinUnknown) [reply src/DelegatingContainer.php]: ✅ 92c5bfd

**Review by XedinUnknown — APPROVED** [review]

**Review by XedinUnknown — APPROVED** [review]
Very cool!
